#!/usr/bin/env node
// build-tokens.js
//
// Compiles commons/commons/tokens/*.json (W3C DTCG format) → four build artefacts via Style Dictionary v4:
//   commons/branding/generated/tokens.css         ← CSS custom properties (:root)
//   commons/branding/generated/_tokens.scss       ← SCSS variables
//   commons/branding/generated/tokens.js          ← JS module (consumed by lint-html.js)
//   commons/branding/generated/tailwind-tokens.js ← Tailwind theme extension
//
// CSS var names preserve the historical short form (--brand, --brand-dk, etc.) so
// no consumer templates need to change when we upgrade token tooling.
//
// Run: npm run build:tokens   (or)   node pipeline/scripts/build-tokens.js

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Name helpers ──────────────────────────────────────────────────────────────

function cssVarName(tok) {
  // color.brand     → --brand        (strip leading "color" category)
  // color.brand-dk  → --brand-dk
  // logo.height.intake → --logo-height-intake
  // font.size.base  → --font-size-base
  const parts = tok.path;
  return '--' + (parts[0] === 'color' ? parts.slice(1) : parts).join('-');
}

function scssVarName(tok) {
  const parts = tok.path;
  return '$' + (parts[0] === 'color' ? parts.slice(1) : parts).join('-');
}

function resolveValue(tok) {
  // In SD v4 DTCG mode, the resolved value lives in tok.$value (tok.value is
  // only populated after a value transform runs; we skip transforms intentionally
  // to avoid unwanted coercions like hex→rgba).
  const v = tok.$value;
  // fontFamily $value is an array per DTCG spec; join to CSS font-stack string.
  return Array.isArray(v) ? v.join(', ') : String(v);
}

// ── Build ─────────────────────────────────────────────────────────────────────

async function main() {
  // SD v4 is ESM-only; use dynamic import() from CJS.
  const { default: StyleDictionary } = await import('style-dictionary');

  StyleDictionary.registerFormat({
    name: 'css/dataskate-vars',
    format({ dictionary }) {
      const header = [
        '/*',
        ' * AUTO-GENERATED by build-tokens.js from commons/tokens/*.json',
        ' * Edit the JSON sources, not this file.',
        ' */',
        ':root {',
      ];
      const vars = dictionary.allTokens.map(tok => {
        const desc = tok.$description ? `  /* ${tok.$description} */` : '';
        return `  ${cssVarName(tok)}: ${resolveValue(tok)};${desc}`;
      });
      return [...header, ...vars, '}'].join('\n') + '\n';
    },
  });

  StyleDictionary.registerFormat({
    name: 'scss/dataskate-vars',
    format({ dictionary }) {
      const header = [
        '// AUTO-GENERATED by build-tokens.js from commons/tokens/*.json',
        '// Edit the JSON sources, not this file.',
        '',
      ];
      const vars = dictionary.allTokens.map(tok => {
        const desc = tok.$description ? `  // ${tok.$description}` : '';
        return `${scssVarName(tok)}: ${resolveValue(tok)};${desc}`;
      });
      return [...header, ...vars].join('\n') + '\n';
    },
  });

  StyleDictionary.registerFormat({
    name: 'js/dataskate-module',
    format({ dictionary }) {
      const entries = dictionary.allTokens
        .map(tok => `  ${JSON.stringify(cssVarName(tok))}: ${JSON.stringify(resolveValue(tok))}`)
        .join(',\n');
      return (
        '/* AUTO-GENERATED by build-tokens.js — edit commons/tokens/*.json, not this file */\n' +
        `module.exports = {\n${entries}\n};\n`
      );
    },
  });

  StyleDictionary.registerFormat({
    name: 'js/tailwind-tokens',
    format({ dictionary }) {
      const colors     = {};
      const fontSize   = {};
      const fontFamily = {};
      const lineHeight = {};
      const spacing    = {};
      const screens    = {};

      for (const tok of dictionary.allTokens) {
        const [cat, ...rest] = tok.path;
        const val = resolveValue(tok);
        if      (cat === 'color')                                colors[rest.join('-')]                = val;
        else if (cat === 'font' && rest[0] === 'size')           fontSize[rest.slice(1).join('-')]     = val;
        else if (cat === 'font' && rest[0] === 'family')         fontFamily[rest.slice(1).join('-')]   = val;
        else if (cat === 'font' && rest[0] === 'lineHeight')     lineHeight[rest.slice(1).join('-')]   = val;
        else if (cat === 'space')                                spacing[rest.join('-')]               = val;
        else if (cat === 'breakpoint')                           screens[rest.join('-')]               = val;
      }

      const config = { colors, fontSize, fontFamily, lineHeight, spacing, screens };
      return (
        '/* AUTO-GENERATED — edit commons/tokens/*.json, not this file */\n' +
        `module.exports = ${JSON.stringify(config, null, 2)};\n`
      );
    },
  });

  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: 'silent' },
    source: ['commons/tokens/**/*.json'],
    platforms: {
      css: {
        buildPath: 'commons/branding/generated/',
        files: [{ destination: 'tokens.css',          format: 'css/dataskate-vars'  }],
      },
      scss: {
        buildPath: 'commons/branding/generated/',
        files: [{ destination: '_tokens.scss',         format: 'scss/dataskate-vars' }],
      },
      js: {
        buildPath: 'commons/branding/generated/',
        files: [{ destination: 'tokens.js',            format: 'js/dataskate-module' }],
      },
      tailwind: {
        buildPath: 'commons/branding/generated/',
        files: [{ destination: 'tailwind-tokens.js',   format: 'js/tailwind-tokens'  }],
      },
    },
  });

  await sd.buildAllPlatforms();

  // Mirror CSS to portal/public so the Engagement Portal picks up palette
  // changes without a manual copy step.
  const src  = path.resolve(__dirname, '../../commons/branding/generated/tokens.css');
  const dest = path.resolve(__dirname, '../../portal/public/tokens.css');
  fs.copyFileSync(src, dest);

  console.log('✓ tokens.css + _tokens.scss + tokens.js + tailwind-tokens.js → commons/branding/generated/');
  console.log('✓ tokens.css  → portal/public/tokens.css');
}

main().catch(err => { console.error(err); process.exit(1); });
