#!/usr/bin/env node
// build-tokens.js
//
// Compiles tokens/*.json → commons/branding/generated/tokens.css
// via Style Dictionary. Replaces the hand-maintained palette block in
// shared-base.css.html.
//
// Run: npm run build:tokens   (or)   node build-tokens.js

'use strict';
const StyleDictionary = require('style-dictionary');

// Custom CSS format: produces exactly the same --brand, --brand-dk, etc.
// custom-property names the existing CSS uses, so consumers don't need to
// change.  Default Style Dictionary CSS format names variables --color-brand,
// which would break every existing template.  We use a custom format that
// emits the historical short names.
StyleDictionary.registerFormat({
  name: 'css/dataskate-vars',
  formatter: function({ dictionary, file }) {
    const lines = ['/*'];
    lines.push(' * AUTO-GENERATED by build-tokens.js from tokens/*.json');
    lines.push(' * Edit the JSON sources, not this file.');
    lines.push(' */');
    lines.push(':root {');
    for (const tok of dictionary.allTokens) {
      // Map: color.brand     → --brand
      //      color.brand-dk  → --brand-dk
      //      logo.height.intake → --logo-height-intake
      //      font.size.base  → --font-size-base
      const parts = tok.path;
      let name;
      if (parts[0] === 'color') {
        name = '--' + parts.slice(1).join('-');
      } else {
        name = '--' + parts.join('-');
      }
      const comment = tok.comment ? `  /* ${tok.comment} */` : '';
      lines.push(`  ${name}: ${tok.value};${comment}`);
    }
    lines.push('}');
    return lines.join('\n') + '\n';
  }
});

const sd = StyleDictionary.extend({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      buildPath: 'commons/branding/generated/',
      files: [{
        destination: 'tokens.css',
        format: 'css/dataskate-vars'
      }]
    },
    // Also emit a JS module so build-time consumers (lint, etc.) can read tokens
    // without re-parsing the JSON tree.
    js: {
      buildPath: 'commons/branding/generated/',
      transformGroup: 'js',
      files: [{
        destination: 'tokens.js',
        format: 'javascript/module-flat'
      }]
    }
  }
});

sd.buildAllPlatforms();
console.log('✓ Tokens built → commons/branding/generated/tokens.css + tokens.js');
