#!/usr/bin/env node
// build-tokens.js
//
// Compiles tokens/*.json → commons/branding/generated/tokens.css
// via Style Dictionary. Also copies the output to firebase/public/tokens.css
// so the Engagement Portal picks up palette changes without a manual copy.
//
// Run: npm run build:tokens   (or)   node build-tokens.js

'use strict';
const fs = require('fs');
const path = require('path');
const StyleDictionary = require('style-dictionary');

// Custom CSS format: produces exactly the same --brand, --brand-dk, etc.
// custom-property names the existing CSS uses, so consumers don't need to
// change.  Default Style Dictionary CSS format names variables --color-brand,
// which would break every existing template.  We use a custom format that
// emits the historical short names.
StyleDictionary.registerFormat({
  name: 'css/dataskate-vars',
  formatter: function({ dictionary, file }) {
    const lines = ['/*'];
    lines.push(' * AUTO-GENERATED by build-tokens.js from tokens/*.json');
    lines.push(' * Edit the JSON sources, not this file.');
    lines.push(' */');
    lines.push(':root {');
    for (const tok of dictionary.allTokens) {
      // Map: color.brand     → --brand
      //      color.brand-dk  → --brand-dk
      //      logo.height.intake → --logo-height-intake
      //      font.size.base  → --font-size-base
      const parts = tok.path;
      let name;
      if (parts[0] === 'color') {
        name = '--' + parts.slice(1).join('-');
      } else {
        name = '--' + parts.join('-');
      }
      const comment = tok.comment ? `  /* ${tok.comment} */` : '';
      lines.push(`  ${name}: ${tok.value};${comment}`);
    }
    lines.push('}');
    return lines.join('\n') + '\n';
  }
});

// Custom JS format: stable output without the timestamp Style Dictionary's
// built-in javascript/module-flat injects, so the generated file doesn't
// produce noisy git diffs on every build:tokens run.
StyleDictionary.registerFormat({
  name: 'js/dataskate-module',
  formatter: function({ dictionary }) {
    const entries = dictionary.allTokens
      .map(tok => `  ${JSON.stringify(tok.name)}: ${JSON.stringify(tok.value)}`)
      .join(',\n');
    return `/* AUTO-GENERATED by build-tokens.js — edit tokens/*.json, not this file */\nmodule.exports = {\n${entries}\n};\n`;
  }
});

const sd = StyleDictionary.extend({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      buildPath: 'commons/branding/generated/',
      files: [{
        destination: 'tokens.css',
        format: 'css/dataskate-vars'
      }]
    },
    // Also emit a JS module so build-time consumers (lint, etc.) can read tokens
    // without re-parsing the JSON tree.
    js: {
      buildPath: 'commons/branding/generated/',
      transformGroup: 'js',
      files: [{
        destination: 'tokens.js',
        format: 'js/dataskate-module'
      }]
    }
  }
});

sd.buildAllPlatforms();

// Copy to firebase/public so the Engagement Portal stays in sync
const src  = path.resolve(__dirname, '../commons/branding/generated/tokens.css');
const dest = path.resolve(__dirname, '../firebase/public/tokens.css');
fs.copyFileSync(src, dest);

console.log('✓ Tokens built → commons/branding/generated/tokens.css + tokens.js');
console.log('✓ Copied       → firebase/public/tokens.css');
