#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# smoke-test.sh — Post-deployment smoke tests for {{PROJECT_NAME}}
#
# Generated by BMAD scaffold for pattern: {{PRIMARY_PATTERN}}
# Run AFTER deployment to verify the live API is reachable and returns
# the expected HTTP status for each endpoint.
#
# Usage:
#   chmod +x smoke-test.sh
#   BASE_URL=https://{{PROJECT_NAME}}.cloudhub.io/api/v1 \
#   CLIENT_ID=<your-client-id> \
#   CLIENT_SECRET=<your-client-secret> \
#   ./smoke-test.sh [ENV]
#
# ENV argument: dev | uat | prod (default: dev)
#
# Exit codes:
#   0 = all smoke tests passed
#   1 = one or more tests failed
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ENV="${1:-dev}"
BASE_URL="${BASE_URL:-https://{{PROJECT_NAME}}.${ENV}.cloudhub.io/api/v1}"
CLIENT_ID="${CLIENT_ID:-}"
CLIENT_SECRET="${CLIENT_SECRET:-}"
CORRELATION_ID="smoke-$(date +%s)-$$"

PASS=0
FAIL=0

# Colour codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ── Helper ────────────────────────────────────────────────────────────────────

check() {
  local name="$1"
  local expected_status="$2"
  local actual_status="$3"
  local body="$4"

  if [ "$actual_status" -eq "$expected_status" ]; then
    echo -e "${GREEN}  PASS${NC} ${name} → HTTP ${actual_status}"
    PASS=$((PASS + 1))
  else
    echo -e "${RED}  FAIL${NC} ${name} → expected HTTP ${expected_status}, got HTTP ${actual_status}"
    echo "       Body: ${body:0:200}"
    FAIL=$((FAIL + 1))
  fi
}

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Smoke Tests: {{PROJECT_NAME}} [${ENV}]"
echo "  Base URL:    ${BASE_URL}"
echo "  Correlation: ${CORRELATION_ID}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Auth Token (if oauth2-client-credentials) ─────────────────────────────────
# TODO: Enable this block when security.apiAuth = oauth2-client-credentials
# TOKEN=$(curl -s -X POST "${BASE_URL%/api*}/oauth2/token" \
#   -H "Content-Type: application/x-www-form-urlencoded" \
#   -d "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}" \
#   | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])")
# AUTH_HEADER="Authorization: Bearer ${TOKEN}"

# For client-id enforcement:
AUTH_HEADER="client_id: ${CLIENT_ID}"
AUTH_SECRET_HEADER="client_secret: ${CLIENT_SECRET}"

# ── Smoke Test 1: Health Check ─────────────────────────────────────────────────
echo "── Health & Connectivity ─────────────────────────────"
RESPONSE=$(curl -s -o /tmp/smoke-body.txt -w "%{http_code}" \
  -H "X-Correlation-ID: ${CORRELATION_ID}-health" \
  "${BASE_URL}/health" 2>/dev/null || echo "000")
BODY=$(cat /tmp/smoke-body.txt 2>/dev/null || echo "")
check "GET /health — API reachable" 200 "$RESPONSE" "$BODY"

# ── Smoke Test 2: Authentication ──────────────────────────────────────────────
echo ""
echo "── Authentication ────────────────────────────────────"

# Unauthenticated request → 401 expected
RESPONSE=$(curl -s -o /tmp/smoke-body.txt -w "%{http_code}" \
  -H "X-Correlation-ID: ${CORRELATION_ID}-unauth" \
  "${BASE_URL}/{{SMOKE_ENDPOINT_1}}" 2>/dev/null || echo "000")
BODY=$(cat /tmp/smoke-body.txt 2>/dev/null || echo "")
check "No credentials → 401" 401 "$RESPONSE" "$BODY"

# Authenticated request → 200 or 404 (not 401/403)
RESPONSE=$(curl -s -o /tmp/smoke-body.txt -w "%{http_code}" \
  -H "X-Correlation-ID: ${CORRELATION_ID}-auth" \
  -H "${AUTH_HEADER}" \
  "${BASE_URL}/{{SMOKE_ENDPOINT_1}}" 2>/dev/null || echo "000")
BODY=$(cat /tmp/smoke-body.txt 2>/dev/null || echo "")
check "Valid credentials → NOT 401" 200 "$RESPONSE" "$BODY"

# ── Smoke Test 3: Correlation ID Propagation ──────────────────────────────────
echo ""
echo "── Correlation ID ────────────────────────────────────"
RESPONSE=$(curl -s -o /tmp/smoke-body.txt -w "%{http_code}" \
  -H "X-Correlation-ID: smoke-corr-id-test-001" \
  -H "${AUTH_HEADER}" \
  "${BASE_URL}/{{SMOKE_ENDPOINT_1}}" 2>/dev/null || echo "000")
BODY=$(cat /tmp/smoke-body.txt 2>/dev/null || echo "")
# Correlation ID should appear in the response body or X-Correlation-ID response header
RESPONSE_FULL=$(curl -s -i \
  -H "X-Correlation-ID: smoke-corr-id-test-001" \
  -H "${AUTH_HEADER}" \
  "${BASE_URL}/{{SMOKE_ENDPOINT_1}}" 2>/dev/null || echo "")
if echo "$RESPONSE_FULL" | grep -qi "smoke-corr-id-test-001"; then
  echo -e "${GREEN}  PASS${NC} Correlation ID echoed in response"
  PASS=$((PASS + 1))
else
  echo -e "${YELLOW}  WARN${NC} Correlation ID not found in response headers/body (may be in log only)"
fi

# ── Smoke Test 4: Input Validation (400) ──────────────────────────────────────
echo ""
echo "── Input Validation ──────────────────────────────────"
RESPONSE=$(curl -s -o /tmp/smoke-body.txt -w "%{http_code}" \
  -X POST \
  -H "Content-Type: application/json" \
  -H "X-Correlation-ID: ${CORRELATION_ID}-validation" \
  -H "${AUTH_HEADER}" \
  -d '{}' \
  "${BASE_URL}/{{SMOKE_ENDPOINT_POST}}" 2>/dev/null || echo "000")
BODY=$(cat /tmp/smoke-body.txt 2>/dev/null || echo "")
check "POST empty body → 400 VALIDATION_ERROR" 400 "$RESPONSE" "$BODY"
# Assert error envelope structure
if echo "$BODY" | python3 -c "import sys,json; d=json.load(sys.stdin); assert 'errorCode' in d and 'correlationId' in d" 2>/dev/null; then
  echo -e "${GREEN}  PASS${NC} Error envelope has errorCode + correlationId"
  PASS=$((PASS + 1))
else
  echo -e "${YELLOW}  WARN${NC} Error envelope schema not validated (check body manually)"
fi

# ── Smoke Test 5: Golden Path POST ────────────────────────────────────────────
echo ""
echo "── Golden Path ───────────────────────────────────────"
# TODO: Replace with a realistic test payload for {{FLOW_TARGET}}
# This should be a valid, non-destructive payload that can be safely sent to any env
RESPONSE=$(curl -s -o /tmp/smoke-body.txt -w "%{http_code}" \
  -X POST \
  -H "Content-Type: application/json" \
  -H "X-Correlation-ID: ${CORRELATION_ID}-golden" \
  -H "${AUTH_HEADER}" \
  -d '{
    "id":        "smoke-test-{{PROJECT_NAME}}-001",
    "name":      "Smoke Test Record",
    "source":    "smoke-test",
    "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
  }' \
  "${BASE_URL}/{{SMOKE_ENDPOINT_POST}}" 2>/dev/null || echo "000")
BODY=$(cat /tmp/smoke-body.txt 2>/dev/null || echo "")
check "POST valid payload → 200/201/202" 201 "$RESPONSE" "$BODY"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Results: ${PASS} passed, ${FAIL} failed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ "$FAIL" -gt 0 ]; then
  echo -e "${RED}  ✗ Smoke tests FAILED — do not promote to next environment${NC}"
  exit 1
else
  echo -e "${GREEN}  ✓ All smoke tests passed${NC}"
  exit 0
fi
