#Hubspot
hubspot.host: "https://api.hubapi.com"
hubspot.private.app.token: "${HUBSPOT_PRIVATE_APP_TOKEN}"
# Azure AD app used for Dynamics 365 FO
d365.resource: "https://zyris-zydev91ed270f8a3f5c58aos.axcloud.dynamics.com"
d365.token.url: "https://login.microsoftonline.com/50111aa1-d297-49ad-9831-7ac385d1edc9/oauth2/v2.0/token"
d365.scopes: "https://zyris-zydev91ed270f8a3f5c58aos.axcloud.dynamics.com/.default"
d365.client.id: "10d729cf-0b18-4b82-8f1e-336be65f838f"
d365.client.secret: "${D365_CLIENT_SECRET}"
#Objectstore Watermark
watermark.default: "2026-04-01T00:00:00Z"
#Batch
batch.blockSize: "100"
#Scheduler
scheduler.frequency.minutes: "1"