C4Component
    title Component View — __API_NAME__ (__CLIENT_NAME__)
    Container_Boundary(api, "__API_NAME__") {
        __COMPONENTS__
    }
    __COMPONENT_RELS__
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")
